### ISSUE TITLE
Steam Auth Web Util not working

### ISSUE THREAD

**Issue by viter0layer** [scholtzm/steam-auth-web-util#3]
[Steam Auth Web Util](http://scholtzm.github.io/steam-auth-web-util/) site doen't work. Until recently the site was working well. Also, your personal [website ](scholtz.me) has stopped working. Apparently there are problems with the hosting.

**Comment by scholtzm** [comment]
Oops, completely forgot to renew. It's back up now.

https://scholtz.me/steam-auth-web-util
https://scholtz.me
